language: elixir
sudo: false
notifications:
  email: false
addons:
  postgresql: "9.4"
services:
  - postgresql

elixir:
  - 1.7

otp_release:
  - 21.1

script:
  - make testing
after_script:
  - make docs
after_success:
  - bash <(curl -s https://codecov.io/bash)
