language: elixir

services:
  - postgresql

addons:
  postgresql: "9.4"

elixir:
  - 1.6
  - 1.5
  - 1.4

otp_release:
  - 21.0
  - 20.3
  - 19.3

matrix:
  exclude:
    - elixir: 1.5
      otp_release: 21.0
    - elixir: 1.4
      otp_release: 21.0

env:
  global:
    - MIX_ENV=test

notifications:
  email: false

sudo: false

script:
  - mix test
  - mix credo
