language: elixir

services:
  - postgresql

addons:
  postgresql: "9.4"

elixir:
  - 1.5
  - 1.4

otp_release:
  - 20.1
  - 19.3

env:
  global:
    - MIX_ENV=test

notifications:
  email: false

sudo: false

script:
  - mix test
  - mix credo
